name: dicoding_story_fl
description:
  Projects from dicoding.com as a practice in advanced navigation, use of media
  (audio, images, and video), and use of maps such as Google Map.
publish_to: "none"
version: 1.1.1+2

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # l10n
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

  # media
  camera: ^0.10.5+9
  camera_windows: ^0.2.2
  image_picker: ^1.1.0

  # dart
  chopper: ^7.4.0
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  get_it: ^7.7.0
  http: ^1.2.1
  json_annotation: ^4.8.1
  logger: ^2.2.0
  logging: ^1.2.0

  # flutter
  cached_network_image: ^3.3.1
  fl_utilities: ^2.0.1
  flex_color_scheme: ^7.3.1
  go_router: ^13.2.4
  package_info_plus: ^4.2.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

  # native build
  icons_launcher: ^2.1.7

  # build
  build_runner: ^2.4.9
  build_verify: ^3.1.0
  chopper_generator: ^7.4.0
  freezed: ^2.5.2
  go_router_builder: ^2.5.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  # generate: true

  assets:
    # assets
    - assets/images/res/

    # licenses
    - assets/fonts/Rubik/OFL.txt

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik/static/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/Rubik/static/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik/static/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik/static/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Rubik/static/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rubik/static/Rubik-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Rubik/static/Rubik-Black.ttf
          weight: 900

        #
        - asset: assets/fonts/Rubik/static/Rubik-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Rubik/static/Rubik-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Rubik/static/Rubik-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Rubik/static/Rubik-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Rubik/static/Rubik-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Rubik/static/Rubik-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Rubik/static/Rubik-BlackItalic.ttf
          weight: 900
          style: italic
