name: dicoding_story_fl
description: Simple media social app for dicoding.com final project.
publish_to: "none"
version: 1.5.0

environment:
  # https://docs.flutter.dev/release/archive
  sdk: 3.3.4
  flutter: 3.19.6

dependencies:
  flutter:
    sdk: flutter

  # l10n
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

  # media
  camera: ^0.11.0+2
  camera_windows: ^0.2.6+1
  image_picker: ^1.1.2

  # maps
  google_maps_flutter: ^2.6.1
  location: ^6.0.2

  # injectable
  get_it: ^7.7.0
  injectable: ^2.4.2

  # dart
  chopper: ^7.4.0
  equatable: ^2.0.7
  freezed_annotation: ^2.4.4
  http: ^1.2.2
  json_annotation: ^4.9.0
  logger: ^2.5.0
  logging: ^1.2.0

  # flutter
  fl_utilities: ^2.0.1
  flex_color_scheme: ^7.3.1
  flutter_native_splash: ^2.4.0
  go_router: ^14.6.2
  package_info_plus: ^8.0.2
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.1
  envied: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # native build
  icons_launcher: ^3.0.0

  # build
  build_runner: ^2.4.9
  build_verify: ^3.1.0
  chopper_generator: ^7.4.0
  freezed: ^2.5.2
  go_router_builder: ^2.7.1
  injectable_generator: ^2.6.1
  json_serializable: ^6.8.0

  # Gitlint
  husky: ^0.1.7
  commitlint_cli: ^0.8.1
  danger_core: ^2.0.0
  envied_generator: ^1.0.1

flutter:
  uses-material-design: true
  # generate: true

  assets:
    # assets
    - assets/images/res/

    # licenses
    - assets/fonts/Rubik/OFL.txt

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik/static/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/Rubik/static/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik/static/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik/static/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Rubik/static/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rubik/static/Rubik-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Rubik/static/Rubik-Black.ttf
          weight: 900

        #
        - asset: assets/fonts/Rubik/static/Rubik-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Rubik/static/Rubik-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Rubik/static/Rubik-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Rubik/static/Rubik-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Rubik/static/Rubik-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Rubik/static/Rubik-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Rubik/static/Rubik-BlackItalic.ttf
          weight: 900
          style: italic
