name: dicoding_story_fl
description:
  Projects from dicoding.com as a practice in advanced navigation, use of media
  (audio, images, and video), and use of maps such as Google Map.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # dart
  chopper: ^7.2.0
  get_it: ^7.6.7

  # flutter
  fl_utilities: ^2.0.1
  go_router: ^13.1.0
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  logger: ^2.2.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  # build
  build_runner: ^2.4.8
  build_verify: ^3.1.0
  chopper_generator: ^7.2.0
  go_router_builder: ^2.4.1

flutter:
  uses-material-design: true
